version: '3'
services:
    apache:
        build: .docker/apache
        container_name: fuffy_apache
        ports:
          - 80:80
        volumes:
          - $VOLUME_MOUNT_PATH.docker/config/vhosts:/etc/apache2/sites-enabled
          - $VOLUME_MOUNT_PATH.:/home/wwwroot/fuffy
        depends_on:
          - php

    mysql:
        image: mysql
        command: "--default-authentication-plugin=mysql_native_password --innodb_use_native_aio=0"
        container_name: fuffy_mysql
        volumes:
            - $VOLUME_MOUNT_PATH.docker/data/db:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: fuffy
            MYSQL_USER: fuffy
            MYSQL_PASSWORD: fuffy

    php:
        build: .docker/php
        container_name: fuffy_php
        volumes:
          - $VOLUME_MOUNT_PATH.:/home/wwwroot/fuffy
        environment:
          - maildev_host=fuffy_maildev
        depends_on:
          - maildev
          - mysql
        links:
          - mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: fuffy_phpmyadmin
        environment:
          PMA_HOST: mysql
          PMA_PORT: 3306
        ports:
            - 8080:80
        links:
            - mysql

    maildev:
        image: djfarrelly/maildev
        container_name: fuffy_maildev
        ports:
          - 8001:80
